sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install pipenv==11.10.0
  - pipenv install --dev
script:
  - pipenv run python setup.py install
  - pipenv run coverage run --source=postman2runner -m unittest discover
after_success:
  - pipenv run coveralls